# Generated by Django 5.1.2 on 2025-01-18 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_users_email'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='user',
        ),
    ]
