# Generated by Django 5.1.2 on 2025-01-18 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_users_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img_url', models.URLField()),
                ('review', models.TextField()),
                ('position', models.CharField(max_length=200)),
            ],
        ),
    ]
